apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-app
  labels:
    app: notification-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
        - name: notification-app
          image: vivverma/notification-srvc:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
spec:
  ports:
    - name: notification-svc
      port: 8085
      # nodePort: 30181
      targetPort: 8085
  selector:
    app: notification-svc