apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-app
  labels:
    app: email-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-app
  template:
    metadata:
      labels:
        app: email-app
    spec:
      containers:
        - name: email-app
          image: lbish/email:1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8085


---
apiVersion: v1
kind: Service
metadata:
  name: email-svc
spec:
  type: NodePort
  ports:
    - name: email-svc
      port: 8085
      # nodePort: 30181
      targetPort: 8085
  selector:
    app: email-app